# This is a basic workflow to help you get started with Actions

name: WorkFlow 2

on:
  repository_dispatch:
    types: [trigger-workflow2]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "Workflow 2 in Repository2 has been triggered!"

    - name: Wait for 5 minutes
      run: sleep 300  # Sleep for 5 minutes
